version: 2.1
jobs:
  build_and_push:
    docker:
      - image: cimg/ruby:2.6.5-node
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-image-{{ .Branch }}
          - v1-image- 
      - run:
          name: イメージの.tarキャッシュがあればロード
          command: |
            set +o pipefail
            docker load -i ~/cache/docker101tutorial.tar | true
      - run:
          name: イメージのビルド
          command: docker build --cache-from=docker101tutorial:latest -t docker101tutorial .
      - run:
          name: イメージのレイヤを.tarにまとめて保存
          command: |
            mkdir -p ~/caches
            docker save -o ~/cache/docker101tutorial.tar docker101tutorial
      - save_cache:
          paths:
            - ~/caches
          key: v1-image-{{ .Branch }}-{{ epoch }}

workflows:
  version: 2
  main:
    jobs:
      - build_and_push
