version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
    steps:
      - checkout

      - setup_remote_docker:
          # docker_layer_caching: true
          version: 17.05.0-ce

      - run:
          name: プライベートイメージの場合は、`docker login`が必要です。
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: 環境変数REGISTORY_URLの設定
          command: echo 'export REGISTORY_URL=${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}' >> $BASH_ENV
      - run:
          name: 指定イメージのpull
          command: docker pull ${REGISTORY_URL}:latest
      - run:
          name: イメージのビルド
          command: docker build -t ${REGISTORY_URL} --cache-from ${REGISTORY_URL} .
      - run:
          name: ビルドしたイメージはそのままpushできます
          command: docker push ${REGISTORY_URL}

workflows:
    version: 2
    main:
      jobs:
        - build
