version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout 
      - run:
          name: イメージのビルド
          command: docker build -t ${CIRCLE_PROJECT_REPONAME} .
      - run:
          name: イメージのレイヤを.tarにまとめて保存
          command: |
            mkdir -p ~/caches
            docker save -o ~/caches/${CIRCLE_PROJECT_REPONAME}.tar ${CIRCLE_PROJECT_REPONAME}
      - persist_to_workspace:
          root: ~/
          paths:
            - caches
  e2e:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      
      - run:
          name: イメージの.tarキャッシュがあればロード
          command: |
            set +o pipefail
            docker load -i ~/caches/${CIRCLE_PROJECT_REPONAME}.tar | true
      - run: docker images
      - run:
          name: Dockerイメージの起動して実行中サービスへアクセス
          command: |
            docker run -d --name circleci-sample -p 3000:3000 ${CIRCLE_PROJECT_REPONAME} 
            sleep 10
            docker exec circleci-sample curl --retry 10 --retry-connrefused http://localhost:3000
      - run:
          name: sample/hello_world.txtファイルの作成
          command: mkdir -p sample && touch sample/hello_world.txt
      - run:
          name: docker cp してリモートDocker環境にフォルダのマウント
          command: |
            docker container create --name tmp -v /sample busybox
            docker cp ./sample/. tmp:/sample
            docker run --volumes-from tmp busybox test -f sample/hello_world.txt       

workflows:
  version: 2
  main:
    jobs:
      - build
      - e2e:
          requires:
            - build
