version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
        environment:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
      - image: circleci/postgres:9.6.9-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: sample_app_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - setup_remote_docker:
          # docker_layer_caching: true
          version: 17.05.0-ce

      - run:
          name: 環境変数REGISTORY_URLの設定
          command: echo 'export REGISTORY_URL=${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}' >> $BASH_ENV
      - run:
          name: 指定イメージのpull
          command: docker pull ${REGISTORY_URL}:latest
      - run:
          name: イメージのビルド
          command: docker build -t ${REGISTORY_URL} --cache-from ${REGISTORY_URL}:latest .
      - run:
          name: ビルドしたイメージはそのままpushできます
          command: docker push ${REGISTORY_URL}:latest

workflows:
    version: 2
    main:
      jobs:
        - build
